import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Image from 'next/image'
import sun from '../public/2k_sun.jpg'
import Header from '../src/components/Header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mihir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Header />
        <div className={styles.section}>
          <div className={styles.sun} />
        </div>
      </div>
    </>
  )
}

export default Home
