import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mihir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <header className={styles.header}>
          <div className={styles.fstar}></div>
          <div className={styles.mstar}></div>
          <div className={styles.bstar}>backstars</div>
          <div>
            e<div>eland</div>
            <div>eclouds</div>
          </div>
        </header>
      </div>
    </>
  )
}

export default Home
